In [1]:
import numpy as np
import pandas as pd

In [2]:
# Question 1
# What's the version of Pandas that you installed?

pd.__version__

'1.4.4'

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

In [4]:
df.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [5]:
# Question 2
# How many columns are in the dataset?

# Answer: 10

In [6]:
df.shape

(20640, 10)

In [7]:
# Question 3
# Which columns in the dataset have missing values?

# Answer: total_bedrooms

In [8]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [9]:
# Question 4
# How many unique values does the ocean_proximity column have?

# Answer: 5

In [10]:
df['ocean_proximity'].nunique()

5

In [11]:
# Question 5
# What's the average value of the median_house_value for the houses located near the bay?

# Answer: 259212

In [12]:
df.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [13]:
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [14]:
# Question 6
# 1. Calculate the average of total_bedrooms column in the dataset.
# 2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
# 3. Now, calculate the average of total_bedrooms again.
# 4. Has it changed?

# Answer: No

In [15]:
df['total_bedrooms'].mean()

537.8705525375618

In [16]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [17]:
df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)

In [18]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [19]:
round(df['total_bedrooms'].mean(), 3)

537.871

In [20]:
# Question 7
# 1. Select all the options located on islands.
# 2. Select only columns housing_median_age, total_rooms, total_bedrooms.
# 3. Get the underlying NumPy array. Let's call it X.
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# 5. Compute the inverse of XTX.
# 6. Create an array y with values [950, 1300, 800, 1000, 1300].
# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# 8. What's the value of the last element of w?

# Answer: 5.6992

In [21]:
data = df[df['ocean_proximity'] == 'ISLAND']

In [22]:
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [23]:
data = data[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [24]:
data

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [25]:
data.shape

(5, 3)

In [26]:
X = data.to_numpy()

In [27]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [28]:
X.shape

(5, 3)

In [29]:
XTX = X.T.dot(X)

In [30]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [31]:
XTX_inv = np.linalg.inv(XTX)

In [32]:
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [33]:
y = np.array([950, 1300, 800, 1000, 1300])

In [34]:
y

array([ 950, 1300,  800, 1000, 1300])

In [35]:
XTX_inv_XT = XTX_inv.dot(X.T)

In [36]:
w = XTX_inv_XT.dot(y)

In [37]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [38]:
# another way to find w
w1 = np.linalg.multi_dot([XTX_inv, X.T, y])

In [39]:
w1

array([23.12330961, -1.48124183,  5.69922946])